/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVoucherRecordsRouteImport } from './routes/_app.voucher-records'
import { Route as AppVoucherEntryRouteImport } from './routes/_app.voucher-entry'
import { Route as AppVoucherCodeMasterRouteImport } from './routes/_app.voucher-code-master'
import { Route as AppTrucksRouteImport } from './routes/_app.trucks'
import { Route as AppOutstandingAccountsRouteImport } from './routes/_app.outstanding-accounts'
import { Route as AppMoneyReceiptRecordsRouteImport } from './routes/_app.money-receipt-records'
import { Route as AppMoneyReceiptRouteImport } from './routes/_app.money-receipt'
import { Route as AppLorryTrackingRouteImport } from './routes/_app.lorry-tracking'
import { Route as AppHireCommissionRouteImport } from './routes/_app.hire-commission'
import { Route as AppConsignmentViewRouteImport } from './routes/_app.consignment-view'
import { Route as AppConsignmentRecordsRouteImport } from './routes/_app.consignment-records'
import { Route as AppConsignmentNoteRouteImport } from './routes/_app.consignment-note'
import { Route as AppCompaniesRouteImport } from './routes/_app.companies'
import { Route as AppChallanRecordsRouteImport } from './routes/_app.challan-records'
import { Route as AppChallanOverviewRouteImport } from './routes/_app.challan-overview'
import { Route as AppChallanNoteRouteImport } from './routes/_app.challan-note'
import { Route as AppCashRegisterRouteImport } from './routes/_app.cash-register'
import { Route as AppBrokersRouteImport } from './routes/_app.brokers'
import { Route as AppBookingViewRouteImport } from './routes/_app.booking-view'
import { Route as AppBookingRegisterRouteImport } from './routes/_app.booking-register'
import { Route as AppBookingEntryRouteImport } from './routes/_app.booking-entry'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppBillRecordsRouteImport } from './routes/_app.bill-records'
import { Route as AppBanksRouteImport } from './routes/_app.banks'
import { Route as AppBankRegisterRouteImport } from './routes/_app.bank-register'
import { Route as AppArrivalViewRouteImport } from './routes/_app.arrival-view'
import { Route as AppArrivalReportRouteImport } from './routes/_app.arrival-report'
import { Route as AppArrivalRecordsRouteImport } from './routes/_app.arrival-records'
import { Route as AppOutstandingTypeRouteImport } from './routes/_app.outstanding.$type'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVoucherRecordsRoute = AppVoucherRecordsRouteImport.update({
  id: '/voucher-records',
  path: '/voucher-records',
  getParentRoute: () => AppRoute,
} as any)
const AppVoucherEntryRoute = AppVoucherEntryRouteImport.update({
  id: '/voucher-entry',
  path: '/voucher-entry',
  getParentRoute: () => AppRoute,
} as any)
const AppVoucherCodeMasterRoute = AppVoucherCodeMasterRouteImport.update({
  id: '/voucher-code-master',
  path: '/voucher-code-master',
  getParentRoute: () => AppRoute,
} as any)
const AppTrucksRoute = AppTrucksRouteImport.update({
  id: '/trucks',
  path: '/trucks',
  getParentRoute: () => AppRoute,
} as any)
const AppOutstandingAccountsRoute = AppOutstandingAccountsRouteImport.update({
  id: '/outstanding-accounts',
  path: '/outstanding-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyReceiptRecordsRoute = AppMoneyReceiptRecordsRouteImport.update({
  id: '/money-receipt-records',
  path: '/money-receipt-records',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyReceiptRoute = AppMoneyReceiptRouteImport.update({
  id: '/money-receipt',
  path: '/money-receipt',
  getParentRoute: () => AppRoute,
} as any)
const AppLorryTrackingRoute = AppLorryTrackingRouteImport.update({
  id: '/lorry-tracking',
  path: '/lorry-tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppHireCommissionRoute = AppHireCommissionRouteImport.update({
  id: '/hire-commission',
  path: '/hire-commission',
  getParentRoute: () => AppRoute,
} as any)
const AppConsignmentViewRoute = AppConsignmentViewRouteImport.update({
  id: '/consignment-view',
  path: '/consignment-view',
  getParentRoute: () => AppRoute,
} as any)
const AppConsignmentRecordsRoute = AppConsignmentRecordsRouteImport.update({
  id: '/consignment-records',
  path: '/consignment-records',
  getParentRoute: () => AppRoute,
} as any)
const AppConsignmentNoteRoute = AppConsignmentNoteRouteImport.update({
  id: '/consignment-note',
  path: '/consignment-note',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppChallanRecordsRoute = AppChallanRecordsRouteImport.update({
  id: '/challan-records',
  path: '/challan-records',
  getParentRoute: () => AppRoute,
} as any)
const AppChallanOverviewRoute = AppChallanOverviewRouteImport.update({
  id: '/challan-overview',
  path: '/challan-overview',
  getParentRoute: () => AppRoute,
} as any)
const AppChallanNoteRoute = AppChallanNoteRouteImport.update({
  id: '/challan-note',
  path: '/challan-note',
  getParentRoute: () => AppRoute,
} as any)
const AppCashRegisterRoute = AppCashRegisterRouteImport.update({
  id: '/cash-register',
  path: '/cash-register',
  getParentRoute: () => AppRoute,
} as any)
const AppBrokersRoute = AppBrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingViewRoute = AppBookingViewRouteImport.update({
  id: '/booking-view',
  path: '/booking-view',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingRegisterRoute = AppBookingRegisterRouteImport.update({
  id: '/booking-register',
  path: '/booking-register',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingEntryRoute = AppBookingEntryRouteImport.update({
  id: '/booking-entry',
  path: '/booking-entry',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBillRecordsRoute = AppBillRecordsRouteImport.update({
  id: '/bill-records',
  path: '/bill-records',
  getParentRoute: () => AppRoute,
} as any)
const AppBanksRoute = AppBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRegisterRoute = AppBankRegisterRouteImport.update({
  id: '/bank-register',
  path: '/bank-register',
  getParentRoute: () => AppRoute,
} as any)
const AppArrivalViewRoute = AppArrivalViewRouteImport.update({
  id: '/arrival-view',
  path: '/arrival-view',
  getParentRoute: () => AppRoute,
} as any)
const AppArrivalReportRoute = AppArrivalReportRouteImport.update({
  id: '/arrival-report',
  path: '/arrival-report',
  getParentRoute: () => AppRoute,
} as any)
const AppArrivalRecordsRoute = AppArrivalRecordsRouteImport.update({
  id: '/arrival-records',
  path: '/arrival-records',
  getParentRoute: () => AppRoute,
} as any)
const AppOutstandingTypeRoute = AppOutstandingTypeRouteImport.update({
  id: '/outstanding/$type',
  path: '/outstanding/$type',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrival-records': typeof AppArrivalRecordsRoute
  '/arrival-report': typeof AppArrivalReportRoute
  '/arrival-view': typeof AppArrivalViewRoute
  '/bank-register': typeof AppBankRegisterRoute
  '/banks': typeof AppBanksRoute
  '/bill-records': typeof AppBillRecordsRoute
  '/billing': typeof AppBillingRoute
  '/booking-entry': typeof AppBookingEntryRoute
  '/booking-register': typeof AppBookingRegisterRoute
  '/booking-view': typeof AppBookingViewRoute
  '/brokers': typeof AppBrokersRoute
  '/cash-register': typeof AppCashRegisterRoute
  '/challan-note': typeof AppChallanNoteRoute
  '/challan-overview': typeof AppChallanOverviewRoute
  '/challan-records': typeof AppChallanRecordsRoute
  '/companies': typeof AppCompaniesRoute
  '/consignment-note': typeof AppConsignmentNoteRoute
  '/consignment-records': typeof AppConsignmentRecordsRoute
  '/consignment-view': typeof AppConsignmentViewRoute
  '/hire-commission': typeof AppHireCommissionRoute
  '/lorry-tracking': typeof AppLorryTrackingRoute
  '/money-receipt': typeof AppMoneyReceiptRoute
  '/money-receipt-records': typeof AppMoneyReceiptRecordsRoute
  '/outstanding-accounts': typeof AppOutstandingAccountsRoute
  '/trucks': typeof AppTrucksRoute
  '/voucher-code-master': typeof AppVoucherCodeMasterRoute
  '/voucher-entry': typeof AppVoucherEntryRoute
  '/voucher-records': typeof AppVoucherRecordsRoute
  '/outstanding/$type': typeof AppOutstandingTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrival-records': typeof AppArrivalRecordsRoute
  '/arrival-report': typeof AppArrivalReportRoute
  '/arrival-view': typeof AppArrivalViewRoute
  '/bank-register': typeof AppBankRegisterRoute
  '/banks': typeof AppBanksRoute
  '/bill-records': typeof AppBillRecordsRoute
  '/billing': typeof AppBillingRoute
  '/booking-entry': typeof AppBookingEntryRoute
  '/booking-register': typeof AppBookingRegisterRoute
  '/booking-view': typeof AppBookingViewRoute
  '/brokers': typeof AppBrokersRoute
  '/cash-register': typeof AppCashRegisterRoute
  '/challan-note': typeof AppChallanNoteRoute
  '/challan-overview': typeof AppChallanOverviewRoute
  '/challan-records': typeof AppChallanRecordsRoute
  '/companies': typeof AppCompaniesRoute
  '/consignment-note': typeof AppConsignmentNoteRoute
  '/consignment-records': typeof AppConsignmentRecordsRoute
  '/consignment-view': typeof AppConsignmentViewRoute
  '/hire-commission': typeof AppHireCommissionRoute
  '/lorry-tracking': typeof AppLorryTrackingRoute
  '/money-receipt': typeof AppMoneyReceiptRoute
  '/money-receipt-records': typeof AppMoneyReceiptRecordsRoute
  '/outstanding-accounts': typeof AppOutstandingAccountsRoute
  '/trucks': typeof AppTrucksRoute
  '/voucher-code-master': typeof AppVoucherCodeMasterRoute
  '/voucher-entry': typeof AppVoucherEntryRoute
  '/voucher-records': typeof AppVoucherRecordsRoute
  '/outstanding/$type': typeof AppOutstandingTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/arrival-records': typeof AppArrivalRecordsRoute
  '/_app/arrival-report': typeof AppArrivalReportRoute
  '/_app/arrival-view': typeof AppArrivalViewRoute
  '/_app/bank-register': typeof AppBankRegisterRoute
  '/_app/banks': typeof AppBanksRoute
  '/_app/bill-records': typeof AppBillRecordsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/booking-entry': typeof AppBookingEntryRoute
  '/_app/booking-register': typeof AppBookingRegisterRoute
  '/_app/booking-view': typeof AppBookingViewRoute
  '/_app/brokers': typeof AppBrokersRoute
  '/_app/cash-register': typeof AppCashRegisterRoute
  '/_app/challan-note': typeof AppChallanNoteRoute
  '/_app/challan-overview': typeof AppChallanOverviewRoute
  '/_app/challan-records': typeof AppChallanRecordsRoute
  '/_app/companies': typeof AppCompaniesRoute
  '/_app/consignment-note': typeof AppConsignmentNoteRoute
  '/_app/consignment-records': typeof AppConsignmentRecordsRoute
  '/_app/consignment-view': typeof AppConsignmentViewRoute
  '/_app/hire-commission': typeof AppHireCommissionRoute
  '/_app/lorry-tracking': typeof AppLorryTrackingRoute
  '/_app/money-receipt': typeof AppMoneyReceiptRoute
  '/_app/money-receipt-records': typeof AppMoneyReceiptRecordsRoute
  '/_app/outstanding-accounts': typeof AppOutstandingAccountsRoute
  '/_app/trucks': typeof AppTrucksRoute
  '/_app/voucher-code-master': typeof AppVoucherCodeMasterRoute
  '/_app/voucher-entry': typeof AppVoucherEntryRoute
  '/_app/voucher-records': typeof AppVoucherRecordsRoute
  '/_app/outstanding/$type': typeof AppOutstandingTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrival-records'
    | '/arrival-report'
    | '/arrival-view'
    | '/bank-register'
    | '/banks'
    | '/bill-records'
    | '/billing'
    | '/booking-entry'
    | '/booking-register'
    | '/booking-view'
    | '/brokers'
    | '/cash-register'
    | '/challan-note'
    | '/challan-overview'
    | '/challan-records'
    | '/companies'
    | '/consignment-note'
    | '/consignment-records'
    | '/consignment-view'
    | '/hire-commission'
    | '/lorry-tracking'
    | '/money-receipt'
    | '/money-receipt-records'
    | '/outstanding-accounts'
    | '/trucks'
    | '/voucher-code-master'
    | '/voucher-entry'
    | '/voucher-records'
    | '/outstanding/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrival-records'
    | '/arrival-report'
    | '/arrival-view'
    | '/bank-register'
    | '/banks'
    | '/bill-records'
    | '/billing'
    | '/booking-entry'
    | '/booking-register'
    | '/booking-view'
    | '/brokers'
    | '/cash-register'
    | '/challan-note'
    | '/challan-overview'
    | '/challan-records'
    | '/companies'
    | '/consignment-note'
    | '/consignment-records'
    | '/consignment-view'
    | '/hire-commission'
    | '/lorry-tracking'
    | '/money-receipt'
    | '/money-receipt-records'
    | '/outstanding-accounts'
    | '/trucks'
    | '/voucher-code-master'
    | '/voucher-entry'
    | '/voucher-records'
    | '/outstanding/$type'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/arrival-records'
    | '/_app/arrival-report'
    | '/_app/arrival-view'
    | '/_app/bank-register'
    | '/_app/banks'
    | '/_app/bill-records'
    | '/_app/billing'
    | '/_app/booking-entry'
    | '/_app/booking-register'
    | '/_app/booking-view'
    | '/_app/brokers'
    | '/_app/cash-register'
    | '/_app/challan-note'
    | '/_app/challan-overview'
    | '/_app/challan-records'
    | '/_app/companies'
    | '/_app/consignment-note'
    | '/_app/consignment-records'
    | '/_app/consignment-view'
    | '/_app/hire-commission'
    | '/_app/lorry-tracking'
    | '/_app/money-receipt'
    | '/_app/money-receipt-records'
    | '/_app/outstanding-accounts'
    | '/_app/trucks'
    | '/_app/voucher-code-master'
    | '/_app/voucher-entry'
    | '/_app/voucher-records'
    | '/_app/outstanding/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/voucher-records': {
      id: '/_app/voucher-records'
      path: '/voucher-records'
      fullPath: '/voucher-records'
      preLoaderRoute: typeof AppVoucherRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voucher-entry': {
      id: '/_app/voucher-entry'
      path: '/voucher-entry'
      fullPath: '/voucher-entry'
      preLoaderRoute: typeof AppVoucherEntryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voucher-code-master': {
      id: '/_app/voucher-code-master'
      path: '/voucher-code-master'
      fullPath: '/voucher-code-master'
      preLoaderRoute: typeof AppVoucherCodeMasterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trucks': {
      id: '/_app/trucks'
      path: '/trucks'
      fullPath: '/trucks'
      preLoaderRoute: typeof AppTrucksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outstanding-accounts': {
      id: '/_app/outstanding-accounts'
      path: '/outstanding-accounts'
      fullPath: '/outstanding-accounts'
      preLoaderRoute: typeof AppOutstandingAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money-receipt-records': {
      id: '/_app/money-receipt-records'
      path: '/money-receipt-records'
      fullPath: '/money-receipt-records'
      preLoaderRoute: typeof AppMoneyReceiptRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money-receipt': {
      id: '/_app/money-receipt'
      path: '/money-receipt'
      fullPath: '/money-receipt'
      preLoaderRoute: typeof AppMoneyReceiptRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lorry-tracking': {
      id: '/_app/lorry-tracking'
      path: '/lorry-tracking'
      fullPath: '/lorry-tracking'
      preLoaderRoute: typeof AppLorryTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hire-commission': {
      id: '/_app/hire-commission'
      path: '/hire-commission'
      fullPath: '/hire-commission'
      preLoaderRoute: typeof AppHireCommissionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consignment-view': {
      id: '/_app/consignment-view'
      path: '/consignment-view'
      fullPath: '/consignment-view'
      preLoaderRoute: typeof AppConsignmentViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consignment-records': {
      id: '/_app/consignment-records'
      path: '/consignment-records'
      fullPath: '/consignment-records'
      preLoaderRoute: typeof AppConsignmentRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consignment-note': {
      id: '/_app/consignment-note'
      path: '/consignment-note'
      fullPath: '/consignment-note'
      preLoaderRoute: typeof AppConsignmentNoteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challan-records': {
      id: '/_app/challan-records'
      path: '/challan-records'
      fullPath: '/challan-records'
      preLoaderRoute: typeof AppChallanRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challan-overview': {
      id: '/_app/challan-overview'
      path: '/challan-overview'
      fullPath: '/challan-overview'
      preLoaderRoute: typeof AppChallanOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challan-note': {
      id: '/_app/challan-note'
      path: '/challan-note'
      fullPath: '/challan-note'
      preLoaderRoute: typeof AppChallanNoteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-register': {
      id: '/_app/cash-register'
      path: '/cash-register'
      fullPath: '/cash-register'
      preLoaderRoute: typeof AppCashRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brokers': {
      id: '/_app/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof AppBrokersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/booking-view': {
      id: '/_app/booking-view'
      path: '/booking-view'
      fullPath: '/booking-view'
      preLoaderRoute: typeof AppBookingViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/booking-register': {
      id: '/_app/booking-register'
      path: '/booking-register'
      fullPath: '/booking-register'
      preLoaderRoute: typeof AppBookingRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/booking-entry': {
      id: '/_app/booking-entry'
      path: '/booking-entry'
      fullPath: '/booking-entry'
      preLoaderRoute: typeof AppBookingEntryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bill-records': {
      id: '/_app/bill-records'
      path: '/bill-records'
      fullPath: '/bill-records'
      preLoaderRoute: typeof AppBillRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banks': {
      id: '/_app/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof AppBanksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank-register': {
      id: '/_app/bank-register'
      path: '/bank-register'
      fullPath: '/bank-register'
      preLoaderRoute: typeof AppBankRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/arrival-view': {
      id: '/_app/arrival-view'
      path: '/arrival-view'
      fullPath: '/arrival-view'
      preLoaderRoute: typeof AppArrivalViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/arrival-report': {
      id: '/_app/arrival-report'
      path: '/arrival-report'
      fullPath: '/arrival-report'
      preLoaderRoute: typeof AppArrivalReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/arrival-records': {
      id: '/_app/arrival-records'
      path: '/arrival-records'
      fullPath: '/arrival-records'
      preLoaderRoute: typeof AppArrivalRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outstanding/$type': {
      id: '/_app/outstanding/$type'
      path: '/outstanding/$type'
      fullPath: '/outstanding/$type'
      preLoaderRoute: typeof AppOutstandingTypeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppArrivalRecordsRoute: typeof AppArrivalRecordsRoute
  AppArrivalReportRoute: typeof AppArrivalReportRoute
  AppArrivalViewRoute: typeof AppArrivalViewRoute
  AppBankRegisterRoute: typeof AppBankRegisterRoute
  AppBanksRoute: typeof AppBanksRoute
  AppBillRecordsRoute: typeof AppBillRecordsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBookingEntryRoute: typeof AppBookingEntryRoute
  AppBookingRegisterRoute: typeof AppBookingRegisterRoute
  AppBookingViewRoute: typeof AppBookingViewRoute
  AppBrokersRoute: typeof AppBrokersRoute
  AppCashRegisterRoute: typeof AppCashRegisterRoute
  AppChallanNoteRoute: typeof AppChallanNoteRoute
  AppChallanOverviewRoute: typeof AppChallanOverviewRoute
  AppChallanRecordsRoute: typeof AppChallanRecordsRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppConsignmentNoteRoute: typeof AppConsignmentNoteRoute
  AppConsignmentRecordsRoute: typeof AppConsignmentRecordsRoute
  AppConsignmentViewRoute: typeof AppConsignmentViewRoute
  AppHireCommissionRoute: typeof AppHireCommissionRoute
  AppLorryTrackingRoute: typeof AppLorryTrackingRoute
  AppMoneyReceiptRoute: typeof AppMoneyReceiptRoute
  AppMoneyReceiptRecordsRoute: typeof AppMoneyReceiptRecordsRoute
  AppOutstandingAccountsRoute: typeof AppOutstandingAccountsRoute
  AppTrucksRoute: typeof AppTrucksRoute
  AppVoucherCodeMasterRoute: typeof AppVoucherCodeMasterRoute
  AppVoucherEntryRoute: typeof AppVoucherEntryRoute
  AppVoucherRecordsRoute: typeof AppVoucherRecordsRoute
  AppOutstandingTypeRoute: typeof AppOutstandingTypeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArrivalRecordsRoute: AppArrivalRecordsRoute,
  AppArrivalReportRoute: AppArrivalReportRoute,
  AppArrivalViewRoute: AppArrivalViewRoute,
  AppBankRegisterRoute: AppBankRegisterRoute,
  AppBanksRoute: AppBanksRoute,
  AppBillRecordsRoute: AppBillRecordsRoute,
  AppBillingRoute: AppBillingRoute,
  AppBookingEntryRoute: AppBookingEntryRoute,
  AppBookingRegisterRoute: AppBookingRegisterRoute,
  AppBookingViewRoute: AppBookingViewRoute,
  AppBrokersRoute: AppBrokersRoute,
  AppCashRegisterRoute: AppCashRegisterRoute,
  AppChallanNoteRoute: AppChallanNoteRoute,
  AppChallanOverviewRoute: AppChallanOverviewRoute,
  AppChallanRecordsRoute: AppChallanRecordsRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppConsignmentNoteRoute: AppConsignmentNoteRoute,
  AppConsignmentRecordsRoute: AppConsignmentRecordsRoute,
  AppConsignmentViewRoute: AppConsignmentViewRoute,
  AppHireCommissionRoute: AppHireCommissionRoute,
  AppLorryTrackingRoute: AppLorryTrackingRoute,
  AppMoneyReceiptRoute: AppMoneyReceiptRoute,
  AppMoneyReceiptRecordsRoute: AppMoneyReceiptRecordsRoute,
  AppOutstandingAccountsRoute: AppOutstandingAccountsRoute,
  AppTrucksRoute: AppTrucksRoute,
  AppVoucherCodeMasterRoute: AppVoucherCodeMasterRoute,
  AppVoucherEntryRoute: AppVoucherEntryRoute,
  AppVoucherRecordsRoute: AppVoucherRecordsRoute,
  AppOutstandingTypeRoute: AppOutstandingTypeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
